### ISSUE TITLE
load_df return type

### ISSUE THREAD

**Issue by paltusplintus** [GSK-Biostatistics/neointerface#2]
The function load_df() says it returns None, but it actually returns   -> [int]

**Comment by BrainAnnex** [comment]
Judging by the code, it appears that it returns:

:return:  A (possibly-empty) list of the Neo4j internal ID's of the created nodes

**Comment by paltusplintus** [comment]
Fixed in this PR: https://github.com/GSK-Biostatistics/neointerface/pull/4
